// import { GetServerSideProps } from "next";
// import { useState, useRef, useEffect } from "react";
// import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
// import { sanityClient } from "../sanity";
// import { Collection } from "../typings";
// import { urlFor } from "../sanity";
// import { Slide } from "react-slideshow-image";
// import {
//   useAddress,
//   useActiveListings,
//   useContract,
//   MediaRenderer,
// } from "@thirdweb-dev/react";
// import Login from "./components/login";
// import { useRouter } from "next/router";
// import Link from "next/link";
// import Header from "./components/header";

// interface Props {
//   collections: Collection[];
// }
// export default function Home({ collections }: Props) {
//   const address = useAddress();
//   console.log("Collections", collections);
//   if (!address) return <Login />;
//   // Sliding upcoming collections
//   const delay = 2500;
//   const [index, setIndex] = useState(0);
//   const timeoutRef = useRef<any>();

//   function resetTimeout() {
//     if (timeoutRef.current) {
//       clearTimeout(timeoutRef.current);
//     }
//   }
//   useEffect(() => {
//     resetTimeout();
//     timeoutRef.current = setTimeout(
//       () =>
//         setIndex((prevIndex) =>
//           prevIndex === collections.length - 1 ? 0 : prevIndex + 1
//         ),
//       delay
//     );

//     return () => {
//       resetTimeout();
//     };
//   }, [index]);

//   // End of sliding Upcoming Collections

//   const { contract } = useContract(
//     process.env.NEXT_PUBLIC_MARKETPLACE_CONTRACT,
//     "marketplace"
//   );
//   const router = useRouter();
//   const { data: listings, isLoading: loadingListings } =
//     useActiveListings(contract);
//   console.log(listings, "hereee");
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <Header />
//       <div className="Home">
//         <div className="sidebar">
//           <Link className="sidebarlink" href="/list">
//             <p>Dashboard</p>
//           </Link>
//           <Link className="sidebarlink" href="/daoproposal/proposal">
//             <p>Proposal</p>
//           </Link>
//           <Link className="sidebarlink" href="/launchpad/launchpad">
//             <p>Launch</p>
//           </Link>
//         </div>
//         <div className="sect">
//           <section className="sect1">
//             {collections.map((item, index) => (
//               <div className="sect1div" key={index}>
//                 <div className="sect1text">
//                   <h1>{item.nftCollectionName}</h1>
//                   <p>
//                     Lorem ipsum dolor, sit amet consectetur adipisicing elit.
//                     Inventore quis deleniti quas alias vitae veniam quos
//                     blanditiis earum voluptas, totam ad, saepe, maxime beatae.
//                     Fugiat ratione ipsum hic quae minus.
//                   </p>
//                   <Link href={`/nfts/${item.slug.current}`} className="">
//                     <button className="sect1btn">HERE...</button>
//                   </Link>
//                 </div>
//                 <div className="sect1img">
//                   <img
//                     src={urlFor(item.mainImage).url()}
//                     alt="nftcollection"
//                     className="w-full h-full"
//                   />
//                 </div>
//               </div>
//             ))}
//           </section>
//           <div>
//             {loadingListings ? (
//               <p className="text-center text-2xl font-Alkalami animate-pulse text-blue-600">
//                 Loading Listings...
//               </p>
//             ) : (
//               // <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-5 mx-auto">
//               <div className="listings">
//                 {listings?.map((listing) => (
//                   <div
//                     onClick={() => router.push(`/listings/${listing.id}`)}
//                     key={listing.id}
//                     // className="flex flex-col card hover:scale-105 transition-all duration-150 ease-out"
//                   >
//                     <div className="column">
//                       <div>
//                         <img src={listing.asset.image} alt="" />
//                       </div>
//                       <div className="pt-2 space-y-2">
//                         <div>
//                           <h2 className="text-lg truncate">
//                             {listing.asset.name}
//                           </h2>
//                           {/* <hr /> */}
//                           <p className="truncate text-sm mt-2 text-gray-600">
//                             {listing.asset.description}
//                           </p>
//                         </div>
//                       </div>
//                     </div>
//                   </div>
//                 ))}
//               </div>
//             )}
//           </div>
//         </div>
//       </div>
//     </div>
//   );
// }

// export const getServerSideProps: GetServerSideProps = async () => {
//   const query = `*[_type == "collection" ]{
//   ...,
//   description,
//   creator->{
//   ...,
// }

//   }`;

//   const collections = await sanityClient.fetch(query);
//   console.log(collections);
//   return {
//     props: {
//       collections,
//     },
//   };
// };
