import { GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { sanityClient } from "../sanity";
import { Collection } from "../typings";
import {
  useAddress,
  useActiveListings,
  useContract,
} from "@thirdweb-dev/react";
import Login from "./components/login";
import { useRouter } from "next/router";
import Link from "next/link";
import Header from "./components/header";

interface Props {
  collections: Collection[];
}
export default function Home({ collections }: Props) {
  const address = useAddress();
  if (!address) return <Login />;
  const { contract } = useContract(
    process.env.NEXT_PUBLIC_MARKETPLACE_CONTRACT,
    "marketplace"
  );
  const router = useRouter();
  const { data: listings, isLoading: loadingListings } =
    useActiveListings(contract);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="h-[40vh] bg-red-500 w-full">
        {collections.map((item) => (
          <Link href={`/nfts/${item.slug.current}`}>
            <p className="font-semibold">{item.nftCollectionName} HERE</p>
          </Link>
        ))}
      </div>
      <div>List HERE</div>
      <div>
        {loadingListings ? (
          <p className="text-center text-2xl font-Alkalami animate-pulse text-blue-600">
            Loading Listings...
          </p>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-5 mx-auto">
            {listings?.map((listing) => (
              <div
                onClick={() => router.push(`/listings/${listing.id}`)}
                key={listing.id}
                className="flex flex-col card hover:scale-105 transition-all duration-150 ease-out"
              >
                <div></div>
                <div className="pt-2 space-y-2">
                  <div>
                    <h2 className="text-lg truncate">{listing.asset.name}</h2>
                    <hr />
                    <p className="truncate text-sm mt-2 text-gray-600">
                      {listing.asset.description}
                    </p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const query = `*[_type == "collection" ]{
  ...,
  description,
  creator->{
  ...,
}
            
            
            
  }`;

  const collections = await sanityClient.fetch(query);
  console.log(collections);
  return {
    props: {
      collections,
    },
  };
};
